QUALITY_SWING = [
    "RELIANCE","TCS","HDFCBANK","ICICIBANK","SBIN","INFY","ITC","LT","AXISBANK","MARUTI",
    "TATASTEEL","ADANIENT","BEL","NHPC","IRFC","HAL","COALINDIA","SUNPHARMA","BHARTIARTL","M&M",
    "TRENT","POWERGRID","NTPC","ONGC","HINDALCO","JSWSTEEL","TATAMOTORS","EICHERMOT","INDHOTEL","DLF"
]

PENNY_STARTER = [
    "SUZLON","YESBANK","IDEA","JPPOWER","RPOWER","IRFC","NHPC","SJVN","UCOBANK","TRIDENT",
    "IDFCFIRSTB","IOB","CENTRALBK","IRB","NBCC","HFCL","SAIL","IOC","BANKINDIA","HUDCO"
]

ALL_STARTER = sorted(set(QUALITY_SWING + PENNY_STARTER))
